name: scalapay
description: "The Scalapay test"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.17
  bloc: 8.1.4
  flutter_bloc: 8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: 2.5.2
  build_runner: 2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
